title: Muhammad Nawfal Bin Zainuddin
description: Robotics Engineer at Datumstruct (S) Pte Ltd
social_link: LinkedIn
social_username: 'https://www.linkedin.com/in/nawfal-zainuddin-070866195/'
github_repo: ''
github_username: nawfalz
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /concomitant_pancake
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
